# Generated by Django 3.2.4 on 2021-08-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinfo',
            name='SpecialSoftware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
