# Generated by Django 3.2.4 on 2021-08-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_labinfo_specialsoftware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinfo',
            name='BasicConfig',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='labinfo',
            name='OS',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='labinfo',
            name='PCspurchasedinYr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='labinfo',
            name='SpecialSoftware',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
