# Generated by Django 3.2.4 on 2021-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210804_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinfo',
            name='NumberofPCs',
            field=models.CharField(max_length=10),
        ),
    ]
