# Generated by Django 3.2.4 on 2021-08-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_labinfo_numberofpcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinfo',
            name='NumberofPCs',
            field=models.IntegerField(),
        ),
    ]
