# Generated by Django 3.2.4 on 2021-08-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_labinfo_numberofpcs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labinfo',
            new_name='AllLabinfo',
        ),
    ]
