# Generated by Django 3.2.4 on 2021-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_lab7a_sw_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab7a_sw_inst',
            name='Version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
