# Generated by Django 3.2.4 on 2021-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_lab7a_sw_inst_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab7a_sw_inst',
            name='SoftwareInstalled',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
