# Generated by Django 3.2.4 on 2021-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_lab7a_sw_inst_softwareinstalled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab7B_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7C_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7D_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7E_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
