# Generated by Django 3.2.4 on 2021-08-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_lab7b_sw_inst_lab7c_sw_inst_lab7d_sw_inst_lab7e_sw_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab', models.CharField(max_length=30)),
                ('tt_file', models.FileField(upload_to='')),
            ],
        ),
    ]
