# Generated by Django 3.2.4 on 2021-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_lab_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_no', models.CharField(max_length=10, unique=True)),
                ('pdf', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
