# Generated by Django 3.2.4 on 2021-09-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_tt_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tt_file',
            old_name='pdf',
            new_name='tt_pdf',
        ),
    ]
