# Generated by Django 3.2.4 on 2021-09-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_rename_pdf_tt_file_tt_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab_Timetable',
        ),
    ]
