# Generated by Django 3.2.4 on 2021-09-07 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_alter_tt_file_tt_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tt_file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
