# Generated by Django 3.2.4 on 2021-09-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_tt_file_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_ready_cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_no', models.CharField(max_length=10, unique=True)),
                ('cert_pdf', models.FileField(upload_to='uploads/lab_ready_cert')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
