# Generated by Django 3.2.4 on 2021-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_lab5a_lab5b_lab5c_lab5d_lab5e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab5A_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
