# Generated by Django 3.2.4 on 2021-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_lab11a_lab11a_sw_inst_lab11b_lab11b_sw_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCC1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputerName', models.CharField(max_length=20, unique=True)),
                ('Processor', models.CharField(max_length=200)),
                ('RAM', models.CharField(max_length=10)),
                ('HardDisk', models.CharField(max_length=10)),
                ('MotherBoard', models.CharField(max_length=20)),
                ('Basic_OS', models.CharField(max_length=50)),
                ('SpecialPurpose', models.CharField(max_length=150)),
                ('DateOfPurchase', models.CharField(max_length=30)),
                ('WorkingStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC1_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputerName', models.CharField(max_length=20, unique=True)),
                ('Processor', models.CharField(max_length=200)),
                ('RAM', models.CharField(max_length=10)),
                ('HardDisk', models.CharField(max_length=10)),
                ('MotherBoard', models.CharField(max_length=20)),
                ('Basic_OS', models.CharField(max_length=50)),
                ('SpecialPurpose', models.CharField(max_length=150)),
                ('DateOfPurchase', models.CharField(max_length=30)),
                ('WorkingStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC2_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputerName', models.CharField(max_length=20, unique=True)),
                ('Processor', models.CharField(max_length=200)),
                ('RAM', models.CharField(max_length=10)),
                ('HardDisk', models.CharField(max_length=10)),
                ('MotherBoard', models.CharField(max_length=20)),
                ('Basic_OS', models.CharField(max_length=50)),
                ('SpecialPurpose', models.CharField(max_length=150)),
                ('DateOfPurchase', models.CharField(max_length=30)),
                ('WorkingStatus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC3_SW_Inst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoftwareInstalled', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
