# Generated by Django 3.2.4 on 2021-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_labcc1_labcc1_sw_inst_labcc2_labcc2_sw_inst_labcc3_labcc3_sw_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('lab_no', models.CharField(max_length=10)),
                ('slot_time', models.TimeField()),
                ('slot_date', models.DateField()),
                ('booked_by', models.CharField(max_length=100)),
            ],
        ),
    ]
