# Generated by Django 3.2.4 on 2021-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_alter_slot_booking_slot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab5A_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAB5A', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
    ]
