# Generated by Django 3.2.4 on 2021-09-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_lab5a_tt_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab5a_tt_booking',
            old_name='LAB5A',
            new_name='TIME',
        ),
    ]
