# Generated by Django 3.2.4 on 2021-09-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
