# Generated by Django 3.2.4 on 2021-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab11A_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab11B_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab5B_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab5C_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab5D_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab5E_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7A_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7B_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7C_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7D_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab7E_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC1_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC2_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabCC3_tt_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.CharField(max_length=20)),
                ('MONDAY', models.CharField(max_length=20)),
                ('TUESDAY', models.CharField(max_length=20)),
                ('WEDNESDAY', models.CharField(max_length=20)),
                ('THURSDAY', models.CharField(max_length=20)),
                ('FRIDAY', models.CharField(max_length=20)),
                ('SATURDAY', models.CharField(max_length=20)),
            ],
        ),
    ]
