# Generated by Django 3.2.4 on 2021-09-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_lab11a_tt_booking_lab11b_tt_booking_lab5b_tt_booking_lab5c_tt_booking_lab5d_tt_booking_lab5e_tt_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab5_Miscellaneous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('File', models.FileField(upload_to='uploads/lab5a_miscellaneous')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
